version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
         name: Run script
         command: |
          docker info
          python3 run.py

